controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController

position_controller:
  ros__parameters:
    joints:
      - left_rev1
      - left_rev2
      - left_rev3
      - left_rev4
      - left_rev5
      - left_rev6
      - left_rev7
      - right_rev1
      - right_rev2
      - right_rev3
      - right_rev4
      - right_rev5
      - right_rev6
      - right_rev7
      - left_left_pris1
      - right_left_pris1

    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
      - effort
