# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - openarm_arm_controller
    - gripper_controller

  openarm_arm_controller:
    type: FollowJointTrajectory
    joints:
      - rev1
      - rev2
      - rev3
      - rev4
      - rev5
      - rev6
    action_ns: follow_joint_trajectory
    default: true
  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - rev7
      - slider_left
      - slider_right
    action_ns: follow_joint_trajectory
    default: true